volumes:
  pg_data:
  static: # Volume для статики
  media:  # Volume для медиа-файлов

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    ports:
      - "9000:8000"  # Прокси на порт 9000
    depends_on:
      - db

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - "9001:80"  # Прокси на порт 9000 для фронтенда
    depends_on:
      - frontend
