version: '3.8'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi:application"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
    volumes:
      - static:/app/static
    command: >
      sh -c "cp -r /app/build/static/* /app/static/ && tail -f /dev/null"
    restart: always

  gateway:
    build:
      context: ./nginx
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/app/static/
      - media:/app/media/
    restart: always

volumes:
  pg_data:
  static:
  media:
